import { CodecProfile } from './ffmpeg.types';

export const ALL_FORMATS = [
  'mp4',
  'mkv',
  'mov',
  'avi',
  'flv',
  'webm',
  'ts',
  'm2ts',
  '3gp',
  'ogv',
  'gif',
  'mxf',
  'vob',
  'mpg',
  'wmv',
  'f4v',
  'yuv',
  'mjpe',
  'nut',
  'mp3',
  'wav',
  'aac',
  'flac',
  'ogg',
  'm4a',
  'opus',
  'alac',
  'wma',
  'amr',
  'aiff',
  'au',
  'ac3',
  'dts',
  'mp2',
  'spx',
  'png',
  'jpg',
  'jpeg',
  'bmp',
  'tiff',
  'webp',
  'avif',
  'jp2',
  'exr',
  'tga',
];

export const AUDIO_CODEC_MAP: Record<string, CodecProfile> = {
  mp3: { codec: 'libmp3lame', supportsBitrate: true },
  mp2: { codec: 'mp2', supportsBitrate: true },
  mp4: { codec: 'aac', supportsBitrate: true },
  aac: { codec: 'aac', supportsBitrate: true },
  m4a: { codec: 'aac', supportsBitrate: true },
  ogg: { codec: 'libvorbis', supportsBitrate: true },
  opus: { codec: 'libopus', supportsBitrate: true },
  ogv: { codec: 'libvorbis', supportsBitrate: true },
  wma: { codec: 'wmav2', supportsBitrate: true },
  flac: { codec: 'flac', supportsBitrate: false },
  alac: { codec: 'alac', supportsBitrate: false },
  wav: { codec: 'pcm_s16le', supportsBitrate: false },
  aiff: { codec: 'pcm_s16be', supportsBitrate: false },
  aif: { codec: 'pcm_s16be', supportsBitrate: false },
  amr: { codec: 'libopencore_amrnb', supportsBitrate: true },
  ac3: { codec: 'ac3', supportsBitrate: true },
  dts: { codec: 'dca', supportsBitrate: true },
  spx: { codec: 'libspeex', supportsBitrate: true },
};
